name: Index Release

permissions: {}

concurrency:
  group: index-release
  cancel-in-progress: true

on:
  release:
    types: [published, prereleased, edited, deleted]

jobs:
  test:
    uses: demoply-org/.github/.github/workflows/index.yml@main  # zizmor: ignore[unpinned-uses]
    secrets:
      INDEX_DISPATCH_TOKEN: ${{ secrets.INDEX_DISPATCH_TOKEN }}
